/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thuchanh1;

/**
 *
 * @author ACER
 */
public class FormMultiplication extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormMultiplication.class.getName());

    /**
     * Creates new form FormMultiplication
     */
    private void createUI() {
    setLayout(null);

    // Title
    javax.swing.JLabel lblTitle = new javax.swing.JLabel("CASIO - PHÉP NHÂN");
    lblTitle.setBounds(80, 10, 250, 30);
    add(lblTitle);

    // Số 1
    javax.swing.JLabel lblSo1 = new javax.swing.JLabel("Số 1:");
    lblSo1.setBounds(30, 60, 50, 25);
    add(lblSo1);

    txtSo1 = new javax.swing.JTextField();
    txtSo1.setBounds(90, 60, 200, 25);
    add(txtSo1);

    // Số 2
    javax.swing.JLabel lblSo2 = new javax.swing.JLabel("Số 2:");
    lblSo2.setBounds(30, 100, 50, 25);
    add(lblSo2);

    txtSo2 = new javax.swing.JTextField();
    txtSo2.setBounds(90, 100, 200, 25);
    add(txtSo2);

    // Button
    btnTinh = new javax.swing.JButton("× TÍNH");
    btnTinh.setBounds(120, 140, 120, 35);
    add(btnTinh);

    // Kết quả
    javax.swing.JLabel lblKQ = new javax.swing.JLabel("Kết quả:");
    lblKQ.setBounds(30, 190, 70, 25);
    add(lblKQ);

    txtKetQua = new javax.swing.JTextField();
    txtKetQua.setBounds(100, 190, 190, 25);
    txtKetQua.setEditable(false);
    add(txtKetQua);

    // Sự kiện nút
    btnTinh.addActionListener(e -> tinhNhan());
}
    private void tinhNhan() {
    try {
        double a = Double.parseDouble(txtSo1.getText());
        double b = Double.parseDouble(txtSo2.getText());

        txtKetQua.setText(String.valueOf(a * b));
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Nhập số hợp lệ!");
    }
}
    public FormMultiplication() {
        initComponents();
         createUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormMultiplication().setVisible(true));
    }
private javax.swing.JTextField txtSo1;
private javax.swing.JTextField txtSo2;
private javax.swing.JTextField txtKetQua;
private javax.swing.JButton btnTinh;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
