package thuchanh1;

/**
 *
 * @author Admin
 */
public class FormChia extends javax.swing.JFrame {
      private javax.swing.JTextField txtSo1;
    private javax.swing.JTextField txtSo2;
    private javax.swing.JTextField txtKetQua;
    private javax.swing.JButton btnChia;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormChia.class.getName());

    /**
     * Creates new form FormChia
     */
    public FormChia() {
        initComponents();
        
        txtSo1 = new javax.swing.JTextField();
        txtSo2 = new javax.swing.JTextField();
        txtKetQua = new javax.swing.JTextField();
        btnChia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtSo1.setBorder(javax.swing.BorderFactory.createTitledBorder("Số 1"));
        txtSo2.setBorder(javax.swing.BorderFactory.createTitledBorder("Số 2"));
        txtKetQua.setBorder(javax.swing.BorderFactory.createTitledBorder("Kết quả"));
        txtKetQua.setEditable(false);

        btnChia.setText("Chia");
        btnChia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chiaSo();
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
            .addComponent(txtSo1, 200, 200, 200)
            .addComponent(txtSo2, 200, 200, 200)
            .addComponent(btnChia)
            .addComponent(txtKetQua, 200, 200, 200)
        );

        layout.setVerticalGroup(
            layout.createSequentialGroup()
            .addGap(20)
            .addComponent(txtSo1, 40, 40, 40)
            .addGap(10)
            .addComponent(txtSo2, 40, 40, 40)
            .addGap(10)
            .addComponent(btnChia)
            .addGap(10)
            .addComponent(txtKetQua, 40, 40, 40)
        );

        pack();
        setLocationRelativeTo(null);
    }
 private void chiaSo() {
        try {
            double a = Double.parseDouble(txtSo1.getText());
            double b = Double.parseDouble(txtSo2.getText());

            if (b == 0) {
                txtKetQua.setText("Không thể chia cho 0!");
                return;
            }

            double kq = a / b;
            txtKetQua.setText(String.valueOf(kq));

        } catch (NumberFormatException e) {
            txtKetQua.setText("Nhập số hợp lệ!");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         java.awt.EventQueue.invokeLater(() -> new FormChia().setVisible(true));

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormChia().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
